export const AGREGAR_SERVICIOS = "AGREGAR_SERVICIOS"
export const AGREGAR_PRODUCTOS = "AGREGAR_PRODUCTOS"
export const LEER_PRODUCTOS = "LEER_PRODUCTOS"
export const LEER_SERVICIOS = "LEER_SERVICIOS"
