export const SET_CURRENT_SERVICE = "SET_CURRENT_SERVICE"
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT"
export const UPDATE_STATUS = "UPDATE_STATUS"
export const CLEAR_ERROR_EVENTO = "CLEAR_ERROR_EVENTO"