export const ERROR_EVENTO = "ERROR_EVENTO"
export const LOADING_EVENTO = "LOADING_EVENTO"
export const LEER_EVENTOS_POR_USUARIO = "LEER_EVENTOS_POR_USUARIO"
export const SET_CURRENT_EVENTO = "SET_CURRENT_EVENTO"
