INSERT INTO arma_tu_fiesta.permiso
    (nombre)
VALUES
    ("insertarNotaria"),
    ("eliminarNotaria"),
    ("actualizarNotaria"),
    ("leerNotaria"),
    ("insertarCliente"),
    ("eliminarCliente"),
    ("actualizarCliente"),
    ("leerCliente"),
    ("insertarEvento"),
    ("eliminarEvento"),
    ("actualizarEvento"),
    ("leerEvento"),
    ("insertarServicioTercerizado"),
    ("eliminarServicioTercerizado"),
    ("actualizarServicioTercerizado"),
    ("leerServicioTercerizado"),
    ("insertarProveedor"),
    ("eliminarProveedor"),
    ("actualizarProveedor"),
    ("leerProveedor")
;