INSERT INTO `arma_tu_fiesta`.`persona` (`cedula`,`p_nombre`,`s_nombre`,`p_apellido`,`s_apellido`,`fecha_nacimiento`,`sexo`,`estado_civil`,`fk_residencia`)
    VALUES
    ('V-20202706','Beatriz','Aurora','Pinzon','Solano','1995-12-20','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'El Valle') as tablaLugar)),
    ('V-20201309','Armando','Enrique ','Mendoza','Saenz','1991-04-04','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Santa Rosalia') as tablaLugar)),
    ('V-7456987','Hermes','','Pinzon','Galarza','1965-01-01','Masculino','Casado',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Coche') as tablaLugar)),
    ('V-9378192','Julia','','Solano','','1970-02-02','Femenino','Casada',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Coche') as tablaLugar)),
    ('V-8741963','Roberto','','Mendoza','','1968-03-03','Masculino','Casado',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Antimano') as tablaLugar)),
    ('E-84659785','Margarita','','Saenz','','1966-05-05','Femenino','Casada',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Antimano') as tablaLugar)),
    ('E-86265784','Nicolas','','Mora','','1996-06-06','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'La Vega') as tablaLugar)),
    ('V-26805693','Marcela','','Valencia','','1993-07-07','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'El Paraiso') as tablaLugar)),
    ('V-22142357','Daniel','','Valencia','','1990-08-08','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'El Junquito') as tablaLugar)),
    ('V-27005921','Patricia','','Fernandez','','1993-09-09','Femenino','Divorciada',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Las Minas') as tablaLugar)),
    ('V-19654963','Hugo','','Lombardi','','1989-10-10','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'San Juan') as tablaLugar)),
    ('V-28745123','Aura','Maria','Fuentes','','2000-11-12','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Santa Teresa') as tablaLugar)),
    ('V-21997002','Michell','','Doinel','','1992-12-11','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = '23 de Enero') as tablaLugar)),
    ('V-21008702','Maria','','Calderon','','1992-01-06','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'La Pastora') as tablaLugar)),
    ('V-30365214','Jenny','','Garcia','','2001-07-20','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Altagracia') as tablaLugar)),
    ('V-29820142','Mariana','','Valdez','','1999-09-01','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'San Jose') as tablaLugar)),
    ('V-31102965','Freddy','Stewart','Contreras','','2002-01-09','Masculino','Soltero',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'San Bernandino') as tablaLugar)),
    ('E-88296365','Catalina','','Angel','','1998-01-28','Femenino','Soltera',
        (SELECT pkLugar FROM (SELECT id_lugar as pkLugar FROM arma_tu_fiesta.lugar WHERE nombre = 'Candelaria') as tablaLugar))
;
