export const ERROR_LUGAR = "ERROR_LUGAR"
export const LOADING_LUGAR = "LOADING_LUGAR"
export const READ_ESTADO = "READ_ESTADO"
export const LEER_MUNICIPIO = "LEER_MUNICIPIO"
export const LEER_PARROQUIA = "LEER_PARROQUIA"

export const SET_CURRENT_ESTADO = "SET_CURRENT_ESTADO"
export const SET_CURRENT_MUNICIPIO = "SET_CURRENT_MUNICIPIO"
export const SET_CURRENT_PARROQUIA = "SET_CURRENT_PARROQUIA"
