export const ERROR_CLIENTE = "ERROR_CLIENTE"
export const CLEAR_ERROR_CLIENTE = "CLEAR_ERROR_CLIENTE"

export const LOADING_CLIENTE = "LOADING_CLIENTE"

export const LEER_CLIENTES = "LEER_CLIENTES"
export const INSERTAR_CLIENTE = "INSERTAR_CLIENTE"
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE"
export const ACTUALIZAR_CLIENTE = "ACTUALIZAR_CLIENTE"
export const SET_CURRENT_CLIENTE = "SET_CURRENT_CLIENTE"
