export const ERROR_CLIENTE = "ERROR_CLIENTE"
export const LOADING_CLIENTE = "LOADING_CLIENTE"

export const LEER_CLIENTES = "LEER_CLIENTES"
export const INSERTAR_CLIENTE = "INSERTAR_CLIENTE"
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE"
export const ACTUALIZAR_CLIENTE = "ACTUALIZAR_CLIENTE"
