export const ERROR_TIP = "ERROR_TIP"
export const LOADING_TIP = "LOADING_TIP"
export const INSERTAR_TIP = "INSERTAR_TIP"
export const ACTUALIZAR_TIP = "ACTUALIZAR_TIP"
export const ELIMINAR_TIP = "ELIMINAR_TIP"
export const LEER_TIPS = "LEER_TIPS"
export const SET_CURRENT_TIP = "SET_CURRENT_TIP"
