export const READ_NOTARIAS = "READ_NOTARIAS"
export const SET_CURRENT_NOTARIA = "SET_CURRENT_NOTARIA"
export const UPDATE_NOTARIA = "UPDATE_NOTARIA"
export const CREATE_NOTARIA = "CREATE_NOTARIA"
export const DELETE_NOTARIA = "DELETE_NOTARIA"

export const ERROR_NOTARIA = "ERROR_NOTARIA"
export const LOADING_NOTARIA = "LOADING_NOTARIA"
