export const READ_NOTARIAS = "READ_NOTARIAS"
export const CREAR_NOTARIA = "CREAR_NOTARIA"
export const SET_CURRENT_NOTARIA = "SET_CURRENT_NOTARIA"
export const UPDATE_NOTARIA = "UPDATE_NOTARIA"
export const ELIMINAR_NOTARIA = "ELIMINAR_NOTARIA"

export const ERROR_NOTARIA = "ERROR_NOTARIA"
export const LOADING_NOTARIA = "LOADING_NOTARIA"
